STD_FILENAMES = {
    'blocks',
    'number',
    'boolean'
}

BUILTINS = {
    'Execute': 'Raw',
    'If': 'Raw',
    'Add': 'Number',
    'Subtract': 'Number',
    'Multiply': 'Number',
    'Divide': 'Number',
    'Mod': 'Number',
    'Power': 'Number',
    'Log': 'Number',
    'Equal': 'Boolean',
    'NotEqual': 'Boolean',
    'Greater': 'Boolean',
    'GreaterOr': 'Boolean',
    'Less': 'Boolean',
    'LessOr': 'Boolean',
    'And': 'Boolean',
    'Or': 'Boolean',
    'Not': 'Boolean',
    'Min': 'Number',
    'Max': 'Number',
    'Abs': 'Number',
    'Sign': 'Number',
    'Ceil': 'Number',
    'Floor': 'Number',
    'Round': 'Number',
    'Frac': 'Number',
    'Trunc': 'Number',
    'Degree': 'Number',
    'Radian': 'Number',
    'Sin': 'Number',
    'Cos': 'Number',
    'Tan': 'Number',
    'Sinh': 'Number',
    'Cosh': 'Number',
    'Tanh': 'Number',
    'Arcsin': 'Number',
    'Arccos': 'Number',
    'Arctan': 'Number',
    'Arctan2': 'Number',
    'Clamp': 'Number',
    'Lerp': 'Number',
    'LerpClamped': 'Number',
    'Unlerp': 'Number',
    'UnlerpClamped': 'Number',
    'Remap': 'Number',
    'Smoothstep': 'Number',
    'Get': 'Raw',
    'Set': 'None'
}

OPERATORS = {
    '+': 'plus',
    '-': 'minus',
    '*': 'mul',
    '/': 'div',
    '%': 'mod',
    '**': 'pow',
    '==': 'eq',
    '!=': 'neq',
    '>': 'gt',
    '>=': 'geq',
    '<': 'lt',
    '<=': 'leq',
    'u-': 'neg',
    'u+': 'pos',
    'u!': 'not',
    '||': 'or',
    '&&': 'and'
}
